name: github-action CICD 
on:
    push:
        branches:
            - main
jobs:
    check-out:
        runs-on: ubuntu-latest
        steps:
          - name: checkout the code
            run : echo "hello"