name: runners
on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            APP_NAME: apple
        steps:
            - name: checkout the code
              uses: actions/checkout@v4
            - name: scan the code
              run: echo "scaining the code"
            - name: deploy if dev 
              if : github.ref == 'refs/heads/dev'
              run: echo "deploy in dev env "
            - name: end of pipline
              run: echo "end of pipline ....."