name: strategy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout code
        run: echo "Code checkout..."

      - name: Build
        run: echo "Application build..."

      - name: Testing
        run: echo "Testing..."

      - name: Deploy
        run: echo "Deploy...''
